version: '3.8'

services:
  api:
    build:
      context: ./api
    ports:
      - "8080:8080"
    networks:
      - la-xarxa

  front:
    build:
      context: ./front
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - la-xarxa

networks:
  la-xarxa:
    external: true
