version: '3.8'

services:
  api:
    build:
      context: ./api
    ports:
      - "8080:8080"
    networks:
      - mynetwork

  front:
    build:
      context: ./front
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - mynetwork

networks:
  mynetwork:
