version: '3.8'

services:
  api:
    build:
      context: ./api
    ports:
      - "8080:8080"
    networks:
      - mynetwork

  front:
    build:
      context: ./front
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certificats:/etc/nginx/certs:ro
    depends_on:
      - api
      - front
    networks:
      - mynetwork

networks:
  mynetwork:
