version: '3.8'

services:
  api:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - TZ=Europe/Paris  # Opcional: Configuració del fus horari
    restart: unless-stopped
